# Generated by Django 4.0.3 on 2022-03-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_assinatura_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
